# Generated by Django 4.0.3 on 2022-04-03 09:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("balance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncomeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Income Category",
                "verbose_name_plural": "Income Categories",
                "ordering": ("id",),
            },
        ),
        migrations.AlterModelOptions(
            name="income",
            options={
                "ordering": ("id",),
                "verbose_name": "Income",
                "verbose_name_plural": "Incomes",
            },
        ),
        migrations.RenameField(
            model_name="income",
            old_name="cyclical_income",
            new_name="recurring_income",
        ),
        migrations.RemoveField(
            model_name="income",
            name="value",
        ),
        migrations.AddField(
            model_name="income",
            name="income_value",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="income",
            name="comment",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="income",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="income",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="income",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="income",
            name="income_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="balance.incomecategory",
            ),
        ),
    ]
