# Generated by Django 4.0.3 on 2022-04-06 16:48

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("balance", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="income",
            options={"ordering": ("-income_date",)},
        ),
        migrations.RemoveField(
            model_name="income",
            name="name",
        ),
        migrations.RemoveField(
            model_name="income",
            name="value",
        ),
        migrations.AddField(
            model_name="income",
            name="income_date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime.now, null=True
            ),
        ),
        migrations.AddField(
            model_name="income",
            name="income_name",
            field=models.CharField(default="zus", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="income",
            name="income_value",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="income",
            name="comment",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="IncomeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("income_category_name", models.CharField(max_length=100, unique=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Income Categories",
            },
        ),
        migrations.AddField(
            model_name="income",
            name="income_category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incomes",
                to="balance.incomecategory",
            ),
            preserve_default=False,
        ),
    ]
