# Generated by Django 4.0.3 on 2022-03-29 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0002_category_alter_income_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
