# Generated by Django 4.0.3 on 2022-04-03 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0002_expense_expensecategory_delete_income_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='cyclical_expense',
            new_name='recurring_expense',
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='balance.expensecategory'),
        ),
    ]
