# Generated by Django 4.0.3 on 2022-04-09 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0003_alter_income_options_expensecategory_expense'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ('-income_date',)},
        ),
    ]
