# Generated by Django 4.0.3 on 2022-03-31 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0003_remove_income_category_delete_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Income',
            new_name='IncomeModel',
        ),
    ]
