# Generated by Django 4.0.3 on 2022-03-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0003_alter_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('1', 'Rent'), ('2', 'Bills'), ('3', 'Groceries'), ('4', 'Dining out'), ('5', 'Transportation'), ('6', 'Entertainment'), ('7', 'Savings'), ('8', 'Clothing'), ('9', 'Beauty'), ('10', 'Health')], max_length=2),
        ),
    ]
