# Generated by Django 4.0.3 on 2022-04-03 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0003_rename_cyclical_expense_expense_recurring_expense_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'ordering': ('expense_category_name',), 'verbose_name_plural': 'Expense Categories'},
        ),
    ]
