# Generated by Django 4.0.3 on 2022-03-31 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0004_rename_income_incomemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IncomeModel',
            new_name='Income',
        ),
    ]
