# Generated by Django 4.0.3 on 2022-04-10 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0004_alter_income_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='income_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='balance.incomecategory'),
        ),
    ]
