# Generated by Django 4.0.3 on 2022-04-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balance", "0004_alter_income_user_alter_incomecategory_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="incomecategory",
            name="comment",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
