# Generated by Django 4.0.3 on 2022-04-01 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0005_rename_incomemodel_income'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={},
        ),
    ]
