# Generated by Django 4.0.3 on 2022-03-31 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0006_alter_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Bills', 'Bills'), ('3', 'Groceries'), ('4', 'Dining out'), ('5', 'Transportation'), ('6', 'Entertainment'), ('7', 'Savings'), ('8', 'Clothing'), ('9', 'Beauty'), ('10', 'Health')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
