# Generated by Django 4.0.3 on 2022-04-01 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0007_incomecategory_alter_income_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='income_category',
        ),
        migrations.DeleteModel(
            name='IncomeCategory',
        ),
    ]
