# Generated by Django 4.0.3 on 2022-04-01 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0007_alter_category_category_name_alter_expense_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='user',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
