# Generated by Django 4.0.3 on 2022-04-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0008_remove_income_income_category_delete_incomecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Income Category',
                'verbose_name_plural': 'Income Categories',
            },
        ),
    ]
