# Generated by Django 4.0.3 on 2022-04-03 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0009_rename_category_expensecategory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ('-expense_date',)},
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='expense_category_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
