# Generated by Django 4.0.3 on 2022-04-01 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0009_incomecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='income_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='balance.incomecategory'),
        ),
    ]
