# Generated by Django 4.0.3 on 2022-04-01 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0010_income_income_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomecategory',
            old_name='name',
            new_name='title',
        ),
    ]
