# Generated by Django 4.0.3 on 2022-04-01 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0011_rename_name_incomecategory_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ('id',), 'verbose_name': 'Income', 'verbose_name_plural': 'Incomes'},
        ),
        migrations.AlterModelOptions(
            name='incomecategory',
            options={'ordering': ('id',), 'verbose_name': 'Income Category', 'verbose_name_plural': 'Income Categories'},
        ),
    ]
